### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by clemcoder** [gremo/symfony-sail#2]
### Description

Hello,

Thank you for this repo.
I try to dockerize an existing app.
Can you please explain me how to launch the container in dev mode ?

I tried : 
- docker compose up --wait => [ERROR] [Entrypoint]: DATABASE_URL is mandatory when APP_ENV is 'prod'
- docker-compose -f docker-compose.dev.yml up -d => nothing happens on localhost

Sorry for my lack of knowledge, I'm new on docker :)
Thanks

**Comment by gremo** [comment]
Hi @clemcoder , no problem, everyone has some lacks. It's super simple if you have Visual Studio Code but I guess you are using another IDE, right?

**Comment by clemcoder** [comment]
Thank you for your answer.
Great I have VS code 👍.

**Comment by gremo** [comment]
So just download the release you want from the quick start section (for example [this](https://github.com/gremo/symfony-sail/releases/latest/download/symfony-sail.zip)), unzip and create an empty `.env.local` file inside the unzipped folder. Then, from VSCode itself, choose <kbd>F1</kbd> and "Reopen in container". You need to install this extension first: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers to see that menu.

I'll try to make the istruction more clear btw, let me know!

**Comment by clemcoder** [comment]
Thank you.
I found these great tutorials for beginners :
https://learn.microsoft.com/en-us/shows/beginners-series-to-dev-containers/?wt.mc_id=devcloud-11496-cxa
https://learn.microsoft.com/en-us/training/modules/use-docker-container-dev-env-vs-code/

Now I know how to do it. Unfortunately it doesn't work. I see 2 errors in
my logs :
[2122 ms] Host server: /bin/sh:
/root/.vscode-remote-containers/bin/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/node:
not found
[2133 ms] Error: stream ended with:0 but wanted:9
        at c
([...]\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\extension\extension.js:24:102284)
        at
[...]\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\extension\extension.js:24:102465
        at s
([...]\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\extension\extension.js:27:5371)
        at Socket.<anonymous>
([...]\.vscode\extensions\ms-vscode-remote.remote-containers-0.309.0\dist\extension\extension.js:27:5541)
        at Socket.emit (node:events:525:35)
        at endReadableNT (node:internal/streams/readable:1359:12)
        at process.processTicksAndRejections
(node:internal/process/task_queues:82:21)

[226955 ms] Container server: Remote to local stream terminated with error:
{
  message: 'connect ENOENT \\\\.\\pipe\\openssh-ssh-agent',
  name: 'Error',
  stack: 'Error: connect ENOENT \\\\.\\pipe\\openssh-ssh-agent\n' +
    '\tat PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)'
}

Do I miss something ?
What's wrong, any idea ?

Thanks again for your help.

**Comment by clemcoder** [comment]
I found te solution here :
https://stackoverflow.com/questions/52113738/starting-ssh-agent-on-windows-10-fails-unable-to-start-ssh-agent-service-erro
Let's go to next problem :)



Le mer. 27 sept. 2023 à 11:57, Clémence Boulay ***@***.***> a
écrit :

**Comment by gremo** [comment]
So what's issues are you still experiencing? Does the issue relates to this project?

**Comment by clemcoder** [comment]
I'm sorry for the delayed response; my work on this topic was on hold.
Currently, I'm unable to connect to my database. I have:

   - - Updated the DATABASE_URL parameter in my .env file.
   - - Updated the following variables in the docker-compose.dev.yml file:

yamlCopy code
environment:
    DATABASE_URL:
***@***.***:3306/myDb?serverVersion=5.6&charset=utf8mb4
    DATABASE_ROOT_PASSWORD: root

I'm getting the error: "An exception occurred in the driver:
SQLSTATE[HY000] [1045] Access denied for user 'root'@'172.18.0.3' (using
password: YES)."

Did I miss something? Thank you again, and have a great day.

Le mer. 4 oct. 2023 à 12:46, Marco Polichetti ***@***.***> a
écrit :

**Comment by gremo** [comment]
Ensure using `db` as host. You cannot change `DATABASE_URL` later and pretend it works with new user or credentials.

This is documented [here](https://github.com/gremo/symfony-sail/blob/main/docs/configuration.md#database-related-variables).
