### ISSUE TITLE
[Bug]: Problem with devcontainer.json

### ISSUE THREAD

**Issue by trukhinyuri** [gremo/symfony-sail#3]
### Which configuration is causing the bug?

Development

### What's included in the downloaded distribution?

- [ ] Database
- [ ] Production configuration
- [ ] Visual Studio code configuration

### OS you are running?

macOS

### Docker Desktop version?

4.28

### Visual Studio Code version?

1.87.2

### Bug description

devcontainer.json does not build in JetBrains IDE 2024.1 and VSCode.

JetBrains IDE Welcome screen -> DevContainers -> New DevContainer (from VCS Project, Docker must be installed.) Insert the git@ link of the repository with devcontainer.json. -> "Build container and Continue"
<img width="1023" alt="image" src="https://github.com/gremo/symfony-sail/assets/1245379/11a01bcc-8457-4f87-8440-e7242d3ea2f8">
<img width="1395" alt="image" src="https://github.com/gremo/symfony-sail/assets/1245379/ac3cf258-7944-4d96-b1a0-619890c3c99e">

**Comment by gremo** [comment]
As far as I can see it miss the `.env.local` file, a new project should always start with that file, even empty 👍
